<?php

use Illuminate\Database\Seeder;

class PublicationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'De Telegraaf 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>42IN07SOl</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);

        \App\Publication::create([
            'source' => 'Brabants Dagblad 1 mei 2016',
            'article' => '<h1>Alin Teri</h1>
                            <p>“Hülya Cigdem uit Tilburg heeft de ProDemosprijs 2015 g<img alt="uitreiking prodemosprijs" src="http://www.alinteri.nl/wp-content/uploads/2015/04/uitreiking-prodemosprijs-300x230.jpg" style="float:right; margin:10px" class="img-responsive">ewonnen voor het project Alin Teri, een burgerinitiatief tegen de relatieve oververtegenwoordiging van Turken in de hennepteelt. Dat is bekendgemaakt tijdens de viering van het eerste lustrum van ProDemos – Huis voor democratie en rechtsstaat.</p>
                            <p>Het motto ‘alin teri’ is Turks voor ‘zweet op je voorhoofd’. Niet met drugshandel, maar met hard werken dient men zijn brood te verdienen, zo luidt de boodschap. Hülya Cigdem roept mensen op de actie te steunen door een eigen profielfoto te doneren: <a href="http://www.alinteri.nl/steun-ons-2/">www.alinteri.nl/steun-ons</a></p>
                            <p><br>
                            <img alt="Koning Willem-Aalexander feliciteert Hulya Cigdem" src="http://www.alinteri.nl/wp-content/uploads/2015/04/Koning-Willem-Aalexander-feliciteert-Hulya-Cigdem-300x294.jpg" style="float:left; margin:10px" class="img-responsive">Uit alle voordrachten voor Meester Burgers vond de jury, bestaande uit Ank Bijleveld-Schouten, Job Cohen en Art Rooijakkers, de inzet van Hülya het meest aansprekend. De jury was onder de indruk van haar actie. Ze zet zich in voor een belangrijke zaak. En het is dapper om zo openlijk voor het bestrijden van hennepteelt in de eigen omgeving uit te komen. Ze spreekt mensen aan op hun verantwoordelijkheid. Het is extra effectief dat het initiatief uit de eigen gemeenschap komt en niet vanuit de autoriteiten. Daarbij is het belangrijk dat Hülya steun krijgt van de autoriteiten&nbsp;én van veel Tilburgers. De jury vindt dit project een mooi voorbeeld van hoe één persoon in staat is veel teweeg te brengen.” bron: ProDemos</p>
                            <p>&nbsp;</p>
                            <p>Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep.</p>
                            <p>&nbsp;</p>
                            <p><img alt="Burgerinitiatief Alinteri013 is open voor iedereen die zich uit wil spreken tegen de thuisteelt van hennep." src="http://www.alinteri.nl/wp-content/uploads/2015/04/logo-223x300.jpg" style="float:right" class="img-responsive">De hennepteelt ondermijnt niet alleen onze rechtstaat, maar ook de Turkse waarde Alin Teri. Alleen al in Tilburg zijn 2.500 mensen werkzaam in de hennepteelt, waarin zo’n 800 miljoen euro omgaat. De Brabantse stad kent tussen de 600 tot 900 illegale wietplantages en het is daarmee uitgegroeid tot één van de grootste bedrijfstakken. De hennephandel vormt een serieuze bedreiging voor de veiligheid en integriteit van de samenleving.</p>
                            <p>Wij, als groep Turkse Nederlanders uit Tilburg, zijn niet blij met de huidige stand van zaken. De relatieve oververtegenwoordiging van de Turkse Nederlanders in de hennepteelt kunnen en willen wij niet accepteren. Dat heeft er voor gezorgd dat we de publiekcampagne AlinTeri013 zijn begonnen.</p>
                        ',
            'video' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/5RG9X5SnHhU" frameborder="0" allowfullscreen></iframe>'
        ]);
    }
}
